on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/hello-world
        with:
          command: tweet
          config: ${{ secrets.TEST_CONFIG }}
          version: ${{github.ref_name}}
      # Use the output from the `hello` step
      - name: Get the output tweet
        run: echo "The tweet was ${{ steps.hello.outputs.tweet }}"